# Generated by Django 6.0.6 on 2026-06-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_workorder_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assigned_to_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workorder',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workorder',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='location_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='safety_notes',
            field=models.TextField(blank=True),
        ),
    ]
