# Generated by Django 6.0.6 on 2026-06-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("icon_class", models.CharField(blank=True, default="", max_length=50)),
                (
                    "price_surcharge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
            ],
            options={
                "verbose_name": "amenity",
                "verbose_name_plural": "amenities",
                "db_table": "amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(max_length=50)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_interval_days",
                    models.IntegerField(blank=True, null=True),
                ),
                ("last_performed", models.DateField(blank=True, null=True)),
                ("next_due", models.DateField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "vendor_contact",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completion_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "maintenance log",
                "verbose_name_plural": "maintenance logs",
                "db_table": "maintenance_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "pricing tier",
                "verbose_name_plural": "pricing tiers",
                "db_table": "pricing_tiers",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RentalSession",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("room_id", models.CharField(max_length=50)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "rental session",
                "verbose_name_plural": "rental sessions",
                "db_table": "rental_sessions",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("room_number", models.CharField(max_length=10)),
                (
                    "sensor_id",
                    models.CharField(
                        help_text="Legacy external device identifier.", max_length=100
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "pricing_tier_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("max_occupants", models.IntegerField(default=1)),
                ("amenities_snapshot", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
                "db_table": "rooms",
                "ordering": ["room_number"],
            },
        ),
        migrations.CreateModel(
            name="RoomAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(max_length=50)),
                ("amenity_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("under_repair", "Under Repair"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "room amenity",
                "verbose_name_plural": "room amenities",
                "db_table": "room_amenities",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room_id", "amenity_id"), name="unique_room_amenity"
                    )
                ],
            },
        ),
    ]
