# Generated by Django 6.0.6 on 2026-06-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_state",
            field=models.CharField(
                blank=True,
                default="vacant",
                help_text="Current occupancy state (from state machine).",
                max_length=30,
            ),
        ),
    ]
