# Generated by Django 6.0.6 on 2026-06-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_dynamic_pricing_rules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayOfWeek',
        ),
        migrations.AlterField(
            model_name='dynamicpricingrule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], help_text='Which weekday(s). Empty means all days in the window.', max_length=3),
        ),
        migrations.AlterField(
            model_name='dynamicpricingrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dynamicpricingrule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicpricingrule',
            name='price_override',
            field=models.DecimalField(decimal_places=2, help_text='Price per night to use when this rule is active.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='dynamicpricingrule',
            name='rule_type',
            field=models.CharField(choices=[('seasonal', 'Seasonal (date range)'), ('day_of_week', 'Day-of-week recurring'), ('special', 'Special date override')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dynamicpricingrule',
            name='start_date',
            field=models.DateField(help_text='Start of the price window.'),
        ),
        migrations.AlterField(
            model_name='dynamicpricingrule',
            name='tier_code',
            field=models.CharField(help_text='Pricing tier code this rule applies to.', max_length=20),
        ),
    ]
