# Generated by Django 6.0.6 on 2026-06-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_fix_dynamic_pricing_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dynamicpricingrule',
            name='unique_tier_day_rule',
        ),
        migrations.AddConstraint(
            model_name='dynamicpricingrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('rule_type', 'day_of_week')), fields=('tier_code', 'rule_type', 'day_of_week'), name='unique_tier_day_rule', violation_error_message='Active day-of-week rule for this tier/day already exists.'),
        ),
    ]
