# Generated by Django 6.0.6 on 2026-06-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_fix_dynamic_pricing_unique_constraint_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=50),
        ),
    ]
