# Generated by Rango on 2026-06-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0001_initial"),
        ("rooms", "0009_seed_room_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_vehicle",
            field=models.ForeignKey(
                blank=True,
                help_text="Vehicle currently associated with this room.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_rooms",
                to="guests.vehicle",
            ),
        ),
    ]
