# Generated by Django 6.0.6 on 2026-06-17 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0010_room_current_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalsession',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle associated with this rental session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_sessions', to='guests.vehicle'),
        ),
    ]
