# Generated by Django 6.0.6 on 2026-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_rental_session_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rooms', models.ManyToManyField(blank=True, related_name='groups', to='rooms.room')),
            ],
            options={
                'verbose_name': 'room group',
                'verbose_name_plural': 'room groups',
                'db_table': 'room_groups',
                'ordering': ['name'],
            },
        ),
    ]
