# Generated by Django 6.0.7 on 2026-07-16 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("rooms", "0013_make_sensor_id_legacy_optional"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterModelOptions(
            name="rentalsession",
            options={
                "ordering": ["-start_time"],
                "permissions": [
                    ("extend_rentalsession", "Can extend a rental session")
                ],
                "verbose_name": "rental session",
                "verbose_name_plural": "rental sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["room_number"],
                "permissions": [
                    ("operate_room", "Can perform front-desk room operations")
                ],
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
            },
        ),
    ]
