# Generated by Django 6.0.6 on 2026-06-12 13:56

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OccupancySession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("room_id", models.CharField(db_index=True, max_length=50)),
                (
                    "guest_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "license_plate",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("check_in", models.DateTimeField(db_index=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "room_type_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "amenities_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "estimated_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("sensor_auto", "Sensor Auto"),
                            ("manual_override", "Manual Override"),
                            ("front_desk", "Front Desk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("checked_out", "Checked Out"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "occupancy session",
                "verbose_name_plural": "occupancy sessions",
                "db_table": "occupancy_sessions",
                "ordering": ["-check_in"],
                "indexes": [
                    models.Index(
                        fields=["room_id", "-check_in"],
                        name="occupancy_s_room_id_ba50b6_idx",
                    ),
                    models.Index(
                        fields=["status"], name="occupancy_s_status_338669_idx"
                    ),
                    models.Index(
                        fields=["check_out", "status"],
                        name="occupancy_s_check_o_4231e7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShiftLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("shift_number", models.IntegerField()),
                ("tier_1_bgo_count", models.IntegerField(default=0)),
                ("tier_2_y0_dndein_count", models.IntegerField(default=0)),
                ("tier_3_boo_count", models.IntegerField(default=0)),
                ("tier_4_buys_count", models.IntegerField(default=0)),
                ("tier_5_s0_luxury_count", models.IntegerField(default=0)),
                (
                    "tier_1_bgo_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "tier_2_y0_dndein_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "tier_3_boo_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "tier_4_buys_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "tier_5_s0_luxury_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "barra_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "ath_subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("logged_by", models.CharField(blank=True, default="", max_length=100)),
                (
                    "verified_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "shift ledger",
                "verbose_name_plural": "shift ledgers",
                "db_table": "shift_ledger",
                "ordering": ["-date", "-shift_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "shift_number"), name="unique_shift_per_day"
                    )
                ],
            },
        ),
    ]
