# Generated by Django 6.0.7 on 2026-07-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupancysession',
            name='source',
            field=models.CharField(choices=[('sensor_auto', 'Sensor Auto'), ('manual_override', 'Manual Override'), ('front_desk', 'Front Desk'), ('room_pulse', 'Room Pulse')], max_length=20),
        ),
    ]
