# Generated by Django 6.0.7 on 2026-07-16 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("revenue", "0002_alter_occupancysession_source"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterModelOptions(
            name="shiftledger",
            options={
                "ordering": ["-date", "-shift_number"],
                "permissions": [
                    ("view_shift_reports", "Can view shift reports"),
                    ("generate_shift", "Can generate and save a shift ledger"),
                    ("generate_management_reports", "Can generate management reports"),
                ],
                "verbose_name": "shift ledger",
                "verbose_name_plural": "shift ledgers",
            },
        ),
    ]
