# Generated by Django 6.0.6 on 2026-06-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("audit_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=50)),
                ("object_type", models.CharField(max_length=50)),
                ("object_id", models.IntegerField(blank=True, null=True)),
                ("previous_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_log_object__8ccc11_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OccupancyEvent",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("room_id", models.CharField(db_index=True, max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("arrival", "Arrival"),
                            ("departure", "Departure"),
                            ("check_in", "Check In"),
                            ("check_out", "Check Out"),
                            ("maintenance", "Maintenance Window"),
                            ("manual_override", "Manual Override"),
                        ],
                        max_length=30,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("sensor_auto", "Automated Sensor"),
                            ("manual_input", "Manual Input"),
                            ("api_call", "API Call"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "occupancy event",
                "verbose_name_plural": "occupancy events",
                "db_table": "occupancy_events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["room_id", "-timestamp"],
                        name="occupancy_e_room_id_813a02_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                ("reading_id", models.AutoField(primary_key=True, serialize=False)),
                ("room_id", models.CharField(db_index=True, max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "distance_mm",
                    models.IntegerField(
                        help_text="Distance in millimeters from sensor."
                    ),
                ),
                (
                    "presence",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="'present' or 'absent' as detected by the raw sensor.",
                        max_length=20,
                    ),
                ),
                ("illuminance", models.IntegerField(blank=True, null=True)),
                ("battery_level", models.FloatField(blank=True, null=True)),
                ("signal_strength_dbm", models.IntegerField(blank=True, null=True)),
                ("raw_payload", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "sensor reading",
                "verbose_name_plural": "sensor readings",
                "db_table": "sensor_readings",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["room_id", "-timestamp"],
                        name="sensor_read_room_id_a13a30_idx",
                    )
                ],
            },
        ),
    ]
