# Generated by Django 6.0.6 on 2026-06-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("occupancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupancyevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("sensor_auto", "Automated Sensor"),
                    ("manual_input", "Manual Input"),
                    ("api_call", "API Call"),
                ],
                default="sensor_auto",
                max_length=20,
            ),
        ),
    ]
