# Generated by Django 6.0.7 on 2026-07-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0002_alter_occupancyevent_source'),
        ('rooms', '0013_make_sensor_id_legacy_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPulseDelivery',
            fields=[
                ('event_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=40)),
                ('generated_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(max_length=100)),
                ('room_count', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', models.JSONField()),
                ('result', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Room Pulse delivery',
                'verbose_name_plural': 'Room Pulse deliveries',
                'db_table': 'room_pulse_deliveries',
                'ordering': ('-received_at',),
            },
        ),
        migrations.AlterField(
            model_name='occupancyevent',
            name='event_type',
            field=models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure'), ('check_in', 'Check In'), ('check_out', 'Check Out'), ('maintenance', 'Maintenance Window'), ('manual_override', 'Manual Override'), ('vehicle_attached', 'Vehicle Attached'), ('vehicle_cleared', 'Vehicle Cleared')], max_length=30),
        ),
        migrations.AlterField(
            model_name='occupancyevent',
            name='source',
            field=models.CharField(choices=[('sensor_auto', 'Automated Sensor'), ('manual_input', 'Manual Input'), ('api_call', 'API Call'), ('room_pulse', 'Room Pulse')], default='sensor_auto', max_length=20),
        ),
        migrations.CreateModel(
            name='RoomPulseRoomState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(db_index=True)),
                ('room_record_id', models.PositiveIntegerField()),
                ('room_name', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('unknown', 'Unknown')], max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('state_source', models.CharField(max_length=40)),
                ('confirmation_streak', models.PositiveIntegerField()),
                ('state_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_observed_at', models.DateTimeField(blank=True, null=True)),
                ('last_observed_state', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('unknown', 'Unknown')], default='', max_length=10)),
                ('last_observed_confidence', models.FloatField(blank=True, null=True)),
                ('camera_id', models.PositiveIntegerField()),
                ('camera_name', models.CharField(max_length=200)),
                ('snapshot_id', models.PositiveIntegerField(blank=True, null=True)),
                ('snapshot_captured_at', models.DateTimeField(blank=True, null=True)),
                ('crop_image_path', models.CharField(blank=True, default='', max_length=1000)),
                ('crop_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('model_version', models.CharField(blank=True, default='', max_length=200)),
                ('stale', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_states', to='occupancy.roompulsedelivery')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_pulse_state', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Pulse room state',
                'verbose_name_plural': 'Room Pulse room states',
                'db_table': 'room_pulse_room_states',
                'ordering': ('room__room_number',),
            },
        ),
    ]
