# Generated by Rango on 2026-06-16

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("make", models.CharField(blank=True, default="", max_length=80)),
                ("model", models.CharField(blank=True, default="", max_length=80)),
                ("color", models.CharField(blank=True, default="", max_length=50)),
                ("license_plate", models.CharField(blank=True, default="", max_length=30)),
                ("license_plate_normalized", models.CharField(blank=True, db_index=True, default="", editable=False, max_length=30)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
                "db_table": "vehicles",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(condition=~Q(("license_plate_normalized", "")), fields=("license_plate_normalized",), name="unique_nonblank_vehicle_plate"),
        ),
    ]
